"""
CONSTANTES
"""
CO2_METRO_G_KM = 40.0
CO2_STCP_G_KM = 109.9
VELOCIDADE_PE_KMH = 5.0    
MAX_WALK_DIST_METERS = 300 
KCAL_PER_MIN = 4.0         
N_SUBPROBLEMAS = 40        
N_GERACOES = 100           
DIFICULDADE_PADRAO = 'dificil'
PENALTY_PE = 500
PENALTY_TRANSBORDO = 5
